baseURL = "https://jp311.github.io/"
languageCode = "zh-CN"
title = "jp311's Blog"
theme = "mini"

defaultContentLanguage = "en"
hasCJKLanuage = true

[permalinks]
posts = "/posts/:title/"

[params]
author = "jp311"
bio = "Software Engineer"

[social]
github = "https://github.com/jp311/"
